#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\IndexController::home
  methods: GET

testJson:
  path: /testJson
  controller: App\Controller\IndexController::testJson
  methods: GET|POST|PUT